### PR TITLE
Fix: Avoids prototype pollution

### PR DESCRIPTION
**Pull request by sttk**
This pr is to fix the vulnerability of prototype pollution.

### CODE REVIEW

**Review by phated — APPROVED** [review]
@sttk sorry for the delay reviewing this. It looks great! Feel free to merge and release it! 🎉 

I also noticed that I'm not a publisher on this package (and maybe others) on npm. Will you add me?

**Comment by sttk** [comment]
Thank you for approving. I merged this pr.

**Comment by sttk** [comment]
@phated I checked that you are already in maintainers on npm about the packages I transfered.

**Review by chrisspradling1980 — COMMENTED** [review]
I guess I've been behind. Thanks

**Pull request merged**
